RentalMoviesTask/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace RentalMoviesTask.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Please enter customer's name")]
        [StringLength(255)]
         public string Name { get; set; }

        public DateTime? birthDate { get; set; }

        public bool IsSubscribedToNewsLetter { get; set; }

        public MembershipTypes MembershipType { get; set;}

        [Display(Name="Membership Type")]
        public byte MembershipTypeId { get; set; }
    }
}

RentalMoviesTask/Controllers/Api/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using RentalMoviesTask.Models;
using RentalMoviesTask.Dtos;
using RentalMoviesTask.App_Start;
using RentalMoviesTask.Controllers.Api;
using AutoMapper;

namespace RentalMoviesTask.Controllers.Api
{
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _context;
        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        //GET/api/customers
        public IHttpActionResult GetCustomers()
        {
            return Ok(_context.customers.ToList().Select(Mapper.Map<Customer,CustomerDto>));
        }
        //GET /api/customers/1
        public IHttpActionResult GetCustomer(int id)
        {
            var customer = _context.customers.SingleOrDefault(c => c.Id == id);
            if (customer == null)
                NotFound();
            return Ok(Mapper.Map<Customer,CustomerDto>(customer));
        }
        //POST /api/customers
        [HttpPost]
        public IHttpActionResult CreateCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            _context.customers.Add(customer);
            _context.SaveChanges();

            customerDto.Id = customer.Id;

            return Created(new Uri(Request.RequestUri+"/"+customer.Id), customerDto);

        }

        //PUT /api/customer/1
        [HttpPut]
        public IHttpActionResult UpdateCustomer(int id, CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var customerInDb = _context.customers.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                return NotFound();

            Mapper.Map(customerDto, customerInDb);
        
            _context.SaveChanges();
            return Ok();
        }

        //DELETE /api/customers/1
        [HttpDelete]
        public IHttpActionResult DeleteCustomer(int id)
        {
            var customerInDb = _context.customers.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                return NotFound();
            _context.customers.Remove(customerInDb);
            _context.SaveChanges();
            return Ok();
         }
    }
}

RentalMoviesTask/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RentalMoviesTask.Models;
using System.Data.Entity;
using RentalMoviesTask.ViewModels;

namespace RentalMoviesTask.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Customer
        public ViewResult Index()
        {
            var customers = _context.customers.Include(c => c.MembershipType).ToList();
            if(User.IsInRole("Admin"))
                return View("IndexAdmin",customers);

            return View("IndexUser", customers);

        }
        [Authorize(Roles ="Admin")]
        public ActionResult New(){

            var membershipTypes = _context.MembershipTypes.ToList();
            var viewModel = new CustomerFormViewModel()
            {
                Customer=new Customer(),
                MembershipTypes = membershipTypes
            };
            return View("CustomerForm", viewModel);   
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer,
                    MembershipTypes = _context.MembershipTypes.ToList()
                };
            return View("CustomerForm", viewModel);
            }
            if (customer.Id == 0)
                _context.customers.Add(customer);       
            else
            {
                var customerInDB = _context.customers.Single(c => customer.Id == c.Id);

                customerInDB.Name = customer.Name;
                customerInDB.IsSubscribedToNewsLetter = customer.IsSubscribedToNewsLetter;
                customerInDB.MembershipTypeId = customer.MembershipTypeId;
                customerInDB.birthDate = customer.birthDate;
            }
            _context.SaveChanges();

            return RedirectToAction("Index", "customers");
        }
        public ActionResult Details(int id)
        {
            var customer = _context.customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return HttpNotFound();

            return View(customer);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var customer = _context.customers.SingleOrDefault(c => c.Id == id);
            //if customer exsit in DB
            if (customer==null)
            {
                return HttpNotFound();
            }
            var viewModel = new CustomerFormViewModel()
            {
                Customer = customer,
                MembershipTypes = _context.MembershipTypes.ToList()

            };
            return View("CustomerForm", viewModel);
        }

    }
}

RentalMoviesTask/Views/Customers/CustomerForm.cshtml
@model RentalMoviesTask.ViewModels.CustomerFormViewModel
@{
    ViewBag.Title = "New";
}

<h1 class="text-center">@Model.Title</h1>
@using (Html.BeginForm("Save", "Customers"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Customer.Name)
        @Html.TextBoxFor(m => m.Customer.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.Name)
    </div>
    <div class="form-group">
        <label for="birthdate">Date of birth</label>
        @Html.TextBoxFor(m => m.Customer.birthDate, "{0:d MMM yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.birthDate)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Customer.MembershipTypeId)
        @Html.DropDownListFor(m => m.Customer.MembershipTypeId, new SelectList(Model.MembershipTypes, "Id", "Name"), "Select Membership Type", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.MembershipTypeId)
    </div>
    <div class="checkbox">
        @Html.CheckBoxFor(m => m.Customer.IsSubscribedToNewsLetter) Subscribed to Newsletter?
    </div>
    @Html.HiddenFor(m => m.Customer.Id)
    @*To prevent security attack(CSRF)*@
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}
@*Enable client side validation*@
@section scripts
    {
    @Scripts.Render("~/bundles/jqueryval")
}

RentalMoviesTask/Views/Customers/Details.cshtml
@model RentalMoviesTask.Models.Customer

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<ul>
    <li>
        Memebership Type: @Model.MembershipType.Name
    </li>
    @if(Model.birthDate != null)
    {
    <li>
        Birthday: @Model.birthDate.Value.ToShortDateString()
    </li>
    }
</ul>

RentalMoviesTask/Views/Customers/IndexAdmin.cshtml
@model IEnumerable<RentalMoviesTask.Models.Customer>

@{
                /**/

                ViewBag.Title = "Customers";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Customers</h1>
@if (!Model.Any())
{
    <p>There is no customers yet.</p>
}
else
{
    <table id="customers" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Customers
                </th>
                <th>
                    Membership Type
                </th>
                <th>
                    Delete Customer
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink((string)customer.Name, "Edit", "Customers", new { id = customer.Id }, null)
                    </td>
                    <td>
                        @customer.MembershipType.Name
                    </td>
                    <td>
                        <button data-customer-id="@customer.Id" class="btn-link js-customer-delete">
                            Delete
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="col-md-12 text-center">
        @Html.ActionLink("Add New Customer", "new", "Customers", new { @type = "button" }, new { @class = "btn btn-primary" })
    </div>
}
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#customers").dataTable();

            $("#customers").on("click", ".js-customer-delete", function () {
                var button = $(this);
                if (confirm("Are you sure you want to delete this customer?")) {
                    $.ajax({
                        url: "/api/customers/" + button.attr("data-customer-id"),
                        method: "DELETE",
                        success: function () {
                            button.parents("tr").remove();
                            location.reload();
                        }
                    });
                }
            });
        });
    </script>
}

RentalMoviesTask/Views/Customers/IndexUser.cshtml
@model IEnumerable<RentalMoviesTask.Models.Customer>

@{
                /**/

                ViewBag.Title = "Customers";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Customers</h1>
@if (!Model.Any())
{
    <p>There is no customers yet.</p>
}
else
{
    <table id="customers" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Customers
                </th>
                <th>
                    Membership Type
                </th>        
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>
                        @customer.Name
                    </td>
                    <td>
                        @customer.MembershipType.Name
                    </td>
                
                </tr>
            }
        </tbody>
    </table>
}
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#customers").dataTable();
        });
    </script>
}